R1: ''
R2: ''

perl_script : ''

sampletable: 'sampletable.tsv'

index_length: 10
barcode_length: 16
pat1: "GTCACAAGGGCCGGCCACAACTCGAG"
pat2: "TGATCCTGCAGTGTCACCTAAATC"
hd: 2
map_pat1: "GTCACAAGGGCCGGCCACAACTCGAG"
map_pat2: "TGATC"
map_pat_rev: "GTACGTCACAATATGATTATCTTTCTAGGGTTAA"
cores: 6
bowtie_base: ""
max_dist_for: 500
max_dist_rev: 20
min_counts: 5
